image: golang:1.13rc1-alpine3.10

cache:
  paths:
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - build

before_script:
  - apk add git

test:
  stage: test
  script:
    - go test ./...

build:
  stage: build
  script:
    - go build