stages:
  - go-build
  - go-test
  - container-build


build:
  stage: go-build
  image: golang:1.13

  script:
    - go build

test:
  stage: go-test
  image: golang:1.13

  script:
    - go test ./... -v

build-image:
  stage: container-build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor --dockerfile Dockerfile