image: golang

stages:
  - build
  - test
  - docker

build:
  stage: build
  script:
    - go build

test:
  stage: test
  script:
    - go test ./... -v

docker:
  stage: docker
  image: docker:18.09.7-dind
  before_script:
    - docker info
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:
    - docker image build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest .
    - docker image push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  after_script:
    - docker logout ${CI_REGISTRY}