image: golang

stages:
  - build
  - test
  - docker

Building Go Binary:
  stage: build
  script:
    - go build

Testing Go App:
  stage: test
  script:
    - go test ./... -v

Building and Pushing Docker image:
  stage: docker
  image: $CI_REGISTRY/group/project/docker:19.03.1
  services:
   - name: $CI_REGISTRY/group/project/docker:19.03.1-dind
     alias: docker
  before_script:
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:
    - docker image build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest .
    - docker image push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest