version: "3.7"
services:
  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: app
    ports:
      - 5432:5432
    volumes:
      - ./resources/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./resources/2-data.sql:/docker-entrypoint-initdb.d/2-data.sql

  db-monitor:
    image: meedan/pgadmin
    ports:
      - 5050:5050
    links:
      - postgresql:postgres-test
    depends_on:
      - postgresql
    #hostname=db
    #user=postgres
    #pass=postgres


  app:
    image: baroprime/prod-rest
    ports:
      - 8081:8080
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_NAME: app
    depends_on:
      - postgresql
