version: "3.7"
services:

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: app
    ports:
      - 5432:5432
    volumes:
      - ./db/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      #- ./db/2-data.sql:/docker-entrypoint-initdb.d/2-data.sql
      
  db-monitor:
    image: meedan/pgadmin
    ports:
      - 5050:5050
    links:
      - db:postgres-test
    depends_on:
      - db
    #hostname=db
    #user=postgres
    #pass=postgres

  app:
    image: baroprime/prod-rest
    build:
      context: .
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: app
    depends_on:
      - db