version: "3.7"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: app
    ports:
      - 5432:5432
  app:
    image: baroprime/prod-rest
    build:
      context: .
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: app
    depends_on:
      - db